In [1]:
import numpy as np


In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [5]:
type(x)

numpy.ndarray

In [7]:
y = np.array([1,2,3])
type(y)

numpy.ndarray

In [8]:
x.shape

(2, 3)

In [9]:
x[1,2]

6

In [10]:
y = x[:,1]

In [11]:
y

array([2, 5], dtype=int32)

In [13]:
np.nan

nan

In [14]:
np.e

2.718281828459045

In [15]:
np.inf

inf

In [16]:
np.empty([2, 2])

array([[1.62827594e-316, 0.00000000e+000],
       [1.58101007e-322, 1.13809967e-268]])

In [17]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.add(1.0, 4.0)


5.0

In [20]:
x1 = np.arange(9.0).reshape((3, 3))

In [21]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [22]:
x2 = np.arange(3.0)

In [23]:
x2

array([0., 1., 2.])

In [24]:
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [25]:
x1+x2

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [26]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [27]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])

In [28]:
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [29]:
np.random.random((5,))

array([0.9902845 , 0.11143819, 0.03167287, 0.55901509, 0.02994812])

In [32]:
x = np.array([1, 2, 3, 4])


In [33]:

x.shape


(4,)

In [34]:
y = np.zeros((2, 3, 4))

In [35]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
y.shape

(2, 3, 4)

In [38]:
y.shape = (3, 8)


In [39]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
y.shape = (3, 6)

ValueError: cannot reshape array of size 24 into shape (3,6)

In [41]:
a = np.arange(6).reshape((3, 2))

In [42]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
a = np.array([[1,2,3], [4,5,6]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [46]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [51]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [52]:
x = np.array([1, 2, 2.5])


In [53]:
x

array([1. , 2. , 2.5])

In [54]:
x.dtype

dtype('float64')

In [55]:
x.astype(int)


array([1, 2, 2])

In [56]:
a = np.array([[1,4],[3,1]])

In [57]:
a

array([[1, 4],
       [3, 1]])

In [58]:
np.sort(a) 

array([[1, 4],
       [1, 3]])

In [59]:
a

array([[1, 4],
       [3, 1]])

In [60]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [61]:
np.sort(a, axis=1)

array([[1, 4],
       [1, 3]])

In [64]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

In [65]:
dtype

[('name', 'S10'), ('height', float), ('age', int)]

In [66]:
values

[('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [67]:
a = np.array(values, dtype=dtype)

In [68]:
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [69]:
np.sort(a, order='height')     

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [70]:
np.sort(a, order=['age', 'height'])   

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [71]:
x = np.array([3, 1, 2])

In [72]:
np.argsort(x)

array([1, 2, 0])

In [73]:
from numpy import array

In [74]:
a = array([1.0, 2.0, 3.0])
b = array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [75]:
a = array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [76]:
a = array([[ 0.0,  0.0,  0.0],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])
b = array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [77]:
x = np.arange(10)
x[2]

2

In [78]:
x.shape = (2,5)

In [79]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:

x[0]

array([0, 1, 2, 3, 4])

In [84]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [85]:
x[:-7]

array([0, 1, 2])

In [91]:
x[1:7:2]
#index 1-7, every 2

array([1, 3, 5])

In [88]:
y = np.arange(35).reshape(5,7)

In [89]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [92]:
y[1:5:2,::3]
#row every 2, col every 3

array([[ 7, 10, 13],
       [21, 24, 27]])

In [93]:
x = np.arange(10,1,-1)

In [94]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [95]:
x[np.array([3, 3, 1, 8])]


array([7, 7, 9, 2])

In [96]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [97]:
y


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [98]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [99]:
b = y>20

In [100]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [101]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [102]:
b[:,5]

array([False, False, False,  True,  True])

In [103]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [104]:
y[[False, False, True, True, True]]

array([[14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [105]:
y[b[:,5]]=10

In [106]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [107]:
def my_func(a):
    return (a[0] + a[-1]) * 0.5

In [108]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [109]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
np.apply_along_axis(my_func, 0, b)

array([4., 5., 6.])

In [111]:
np.apply_along_axis(my_func, 1, b)

array([2., 5., 8.])

In [112]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])

In [113]:
b

array([[8, 1, 7],
       [4, 3, 9],
       [5, 2, 6]])

In [114]:
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [115]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [116]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
np.apply_along_axis(np.diag, -1, b)

array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])