In [1]:
import pandas as pd


In [2]:
pd.__version__


'1.1.5'

In [22]:
colleges = pd.read_csv("ForbesAmericasTopColleges2019.csv")
type(nba)

pandas.core.frame.DataFrame

In [23]:
len(colleges)


650

In [24]:
colleges.describe()

Rank  Undergraduate Population  Student Population     Net Price  \
count  650.00000                650.000000          650.000000    648.000000   
mean   325.50000              10002.692308        12022.290769  22336.947531   
std    187.78312              11162.172430        13175.091581   8269.912032   
min      1.00000                185.000000          386.000000      0.000000   
25%    163.25000               2020.250000         2240.750000  16410.000000   
50%    325.50000               4503.000000         6269.000000  21989.000000   
75%    487.75000              15657.000000        17788.000000  27580.500000   
max    650.00000              65100.000000        75044.000000  47270.000000   

       Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
count         646.000000         650.000000     635.000000       648.000000   
mean        20031.208978       50330.175385   98851.968504        61.597222   
std         11175.869976       13223.055038   14335.249458        22.024781   
min          2975.000000           0.000000   70700.000000         5.000000   
25%          9288.250000       39917.000000   88600.000000        48.000000   
50%         19605.000000       50265.000000   96400.000000        67.000000   
75%         27474.500000       60771.750000  105600.000000        78.000000   
max         50897.000000       75735.000000  158200.000000       100.000000   

         SAT Lower    SAT Upper   ACT Lower   ACT Upper  
count   551.000000   551.000000  553.000000  553.000000  
mean   1110.145191  1308.078040   23.278481   28.441230  
std     127.744079   113.553237    3.729318    3.058115  
min     820.000000  1060.000000   15.000000   20.000000  
25%    1020.000000  1230.000000   21.000000   26.000000  
50%    1080.000000  1290.000000   22.000000   28.000000  
75%    1180.000000  1380.000000   25.000000   31.000000  
max    1530.000000  1590.000000   34.000000   35.000000

In [25]:
colleges["Rank"].value_counts()

647.0    1
304.0    1
376.0    1
372.0    1
368.0    1
        ..
189.0    1
187.0    1
401.0    1
185.0    1
1.0      1
Name: Rank, Length: 650, dtype: int64

In [26]:
colleges.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Rank                      650 non-null    float64
 1   Name                      650 non-null    object 
 2   City                      647 non-null    object 
 3   State                     650 non-null    object 
 4   Public/Private            650 non-null    object 
 5   Undergraduate Population  650 non-null    float64
 6   Student Population        650 non-null    float64
 7   Net Price                 648 non-null    float64
 8   Average Grant Aid         646 non-null    float64
 9   Total Annual Cost         650 non-null    float64
 10  Alumni Salary             635 non-null    float64
 11  Acceptance Rate           648 non-null    float64
 12  SAT Lower                 551 non-null    float64
 13  SAT Upper                 551 non-null    float64
 14  ACT Lower 

In [4]:
import pandas as pd



In [5]:
c1 = pd.read_csv("c1.csv")
c2 = pd.read_csv("c2.csv")

In [6]:
c1.describe()


Rank  Undergraduate Population  Student Population     Net Price  \
count  5.000000                  5.000000            5.000000      5.000000   
mean   3.000000               7813.600000        16273.400000  15262.600000   
std    1.581139               3638.137752         8944.470068   4521.469761   
min    1.000000               4680.000000         8273.000000   9327.000000   
25%    2.000000               5659.000000        11466.000000  13261.000000   
50%    3.000000               6483.000000        12974.000000  14327.000000   
75%    4.000000               8402.000000        17534.000000  18627.000000   
max    5.000000              13844.000000        31120.000000  20771.000000   

       Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
count           5.000000           5.000000       5.000000              5.0   
mean        48447.400000       68715.800000  144980.000000              6.0   
std          3083.499603        1987.431307    6774.363439              1.0   
min         43248.000000       66150.000000  138300.000000              5.0   
25%         48088.000000       67430.000000  139400.000000              5.0   
50%         49870.000000       69109.000000  145200.000000              6.0   
75%         50134.000000       69600.000000  146800.000000              7.0   
max         50897.000000       71290.000000  155200.000000              7.0   

         SAT Lower    SAT Upper  ACT Lower  ACT Upper  
count     5.000000     5.000000   5.000000        5.0  
mean   1446.000000  1570.000000  32.000000       35.0  
std      37.815341    18.708287   0.707107        0.0  
min    1390.000000  1540.000000  31.000000       35.0  
25%    1430.000000  1570.000000  32.000000       35.0  
50%    1460.000000  1570.000000  32.000000       35.0  
75%    1460.000000  1580.000000  32.000000       35.0  
max    1490.000000  1590.000000  33.000000       35.0

In [7]:
c2.describe()

Rank  Undergraduate Population  Student Population     Net Price  \
count   6.000000                  6.000000            6.000000      6.000000   
mean    8.500000               8080.000000        13892.500000  29346.666667   
std     1.870829               5222.180656         9215.999756   4435.287078   
min     6.000000               1002.000000         2238.000000  24242.000000   
25%     7.250000               5315.750000         7405.500000  25735.000000   
50%     8.500000               7287.000000        13112.500000  30313.000000   
75%     9.750000              11925.250000        21294.500000  31027.750000   
max    11.000000              14774.000000        25367.000000  35737.000000   

       Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
count           6.000000           6.000000       6.000000         6.000000   
mean        43305.833333       70929.666667  134050.000000         9.666667   
std          4313.442218        1150.522606    8917.118369         1.861899   
min         36164.000000       68901.000000  127600.000000         8.000000   
25%         41669.750000       70503.250000  128875.000000         8.250000   
50%         43628.000000       71382.500000  131500.000000         9.500000   
75%         46578.500000       71751.750000  133450.000000        10.000000   
max         47836.000000       71827.000000  151600.000000        13.000000   

         SAT Lower    SAT Upper  ACT Lower  ACT Upper  
count     6.000000     6.000000   6.000000   6.000000  
mean   1425.833333  1561.666667  31.500000  34.666667  
std      54.260176    17.224014   1.378405   0.516398  
min    1380.000000  1540.000000  30.000000  34.000000  
25%    1393.750000  1552.500000  31.000000  34.250000  
50%    1412.500000  1560.000000  31.000000  35.000000  
75%    1427.500000  1567.500000  31.750000  35.000000  
max    1530.000000  1590.000000  34.000000  35.000000

In [8]:
c1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Rank                      5 non-null      float64
 1   Name                      5 non-null      object 
 2   City                      5 non-null      object 
 3   State                     5 non-null      object 
 4   Public/Private            5 non-null      object 
 5   Undergraduate Population  5 non-null      float64
 6   Student Population        5 non-null      float64
 7   Net Price                 5 non-null      float64
 8   Average Grant Aid         5 non-null      float64
 9   Total Annual Cost         5 non-null      float64
 10  Alumni Salary             5 non-null      float64
 11  Acceptance Rate           5 non-null      float64
 12  SAT Lower                 5 non-null      float64
 13  SAT Upper                 5 non-null      float64
 14  ACT Lower     

In [9]:
c1["Name"].value_counts()


Harvard University                       1
Yale University                          1
Massachusetts Institute of Technology    1
Stanford University                      1
Princeton University                     1
Name: Name, dtype: int64

In [10]:
c2["Name"].value_counts()


Cornell University                    1
Duke University                       1
University of Pennsylvania            1
California Institute of Technology    1
Dartmouth College                     1
Brown University                      1
Name: Name, dtype: int64

In [11]:
pd.concat([c1, c2],axis=0)

Rank                                   Name          City State  \
0   1.0                     Harvard University     Cambridge    MA   
1   2.0                    Stanford University      Stanford    CA   
2   3.0                        Yale University     New Haven    CT   
3   4.0  Massachusetts Institute of Technology     Cambridge    MA   
4   5.0                   Princeton University     Princeton    NJ   
0   6.0             University of Pennsylvania  Philadelphia    PA   
1   7.0                       Brown University    Providence    RI   
2   8.0     California Institute of Technology      Pasadena    CA   
3   9.0                        Duke University        Durham    NC   
4  10.0                      Dartmouth College       Hanover    NH   
5  11.0                     Cornell University        Ithaca    NY   

  Public/Private  Undergraduate Population  Student Population  Net Price  \
0        Private                   13844.0             31120.0    14327.0   
1        Private                    8402.0             17534.0    13261.0   
2        Private                    6483.0             12974.0    18627.0   
3        Private                    4680.0             11466.0    20771.0   
4        Private                    5659.0              8273.0     9327.0   
0        Private                   13437.0             25367.0    24242.0   
1        Private                    7390.0             10095.0    30205.0   
2        Private                    1002.0              2238.0    24245.0   
3        Private                    7184.0             16130.0    35737.0   
4        Private                    4693.0              6509.0    30421.0   
5        Private                   14774.0             23016.0    31230.0   

   Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
0            49870.0            69600.0       146800.0              5.0   
1            50134.0            69109.0       145200.0              5.0   
2            50897.0            71290.0       138300.0              7.0   
3            43248.0            67430.0       155200.0              7.0   
4            48088.0            66150.0       139400.0              6.0   
0            44801.0            71715.0       133900.0              9.0   
1            42455.0            71050.0       127600.0              8.0   
2            41408.0            68901.0       151600.0              8.0   
3            47836.0            71764.0       132100.0             10.0   
4            47171.0            71827.0       130900.0             10.0   
5            36164.0            70321.0       128200.0             13.0   

   SAT Lower  SAT Upper  ACT Lower  ACT Upper            Website  
0     1460.0     1590.0       32.0       35.0    www.harvard.edu  
1     1390.0     1540.0       32.0       35.0   www.stanford.edu  
2     1460.0     1580.0       32.0       35.0       www.yale.edu  
3     1490.0     1570.0       33.0       35.0        web.mit.edu  
4     1430.0     1570.0       31.0       35.0  www.princeton.edu  
0     1420.0     1560.0       32.0       35.0      www.upenn.edu  
1     1405.0     1570.0       31.0       35.0      www.brown.edu  
2     1530.0     1590.0       34.0       35.0    www.caltech.edu  
3     1380.0     1540.0       31.0       35.0       www.duke.edu  
4     1430.0     1560.0       30.0       34.0  www.dartmouth.edu  
5     1390.0     1550.0       31.0       34.0    www.cornell.edu

In [12]:
col1 = pd.read_csv("col1.csv")
col2 = pd.read_csv("col2.csv")

In [13]:
col1.describe()


Rank
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [14]:
col2.describe()


Undergraduate Population  Student Population     Net Price  \
count                  2.000000            2.000000      2.000000   
mean               11123.000000        24327.000000  13794.000000   
std                 3848.075103         9606.752729    753.775829   
min                 8402.000000        17534.000000  13261.000000   
25%                 9762.500000        20930.500000  13527.500000   
50%                11123.000000        24327.000000  13794.000000   
75%                12483.500000        27723.500000  14060.500000   
max                13844.000000        31120.000000  14327.000000   

       Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
count            2.00000            2.00000        2.00000              2.0   
mean         50002.00000        69354.50000   146000.00000              5.0   
std            186.67619          347.18943     1131.37085              0.0   
min          49870.00000        69109.00000   145200.00000              5.0   
25%          49936.00000        69231.75000   145600.00000              5.0   
50%          50002.00000        69354.50000   146000.00000              5.0   
75%          50068.00000        69477.25000   146400.00000              5.0   
max          50134.00000        69600.00000   146800.00000              5.0   

         SAT Lower    SAT Upper  ACT Lower  ACT Upper  
count     2.000000     2.000000        2.0        2.0  
mean   1425.000000  1565.000000       32.0       35.0  
std      49.497475    35.355339        0.0        0.0  
min    1390.000000  1540.000000       32.0       35.0  
25%    1407.500000  1552.500000       32.0       35.0  
50%    1425.000000  1565.000000       32.0       35.0  
75%    1442.500000  1577.500000       32.0       35.0  
max    1460.000000  1590.000000       32.0       35.0

In [17]:
sum=pd.concat([col1, col2],axis=1)

In [18]:
sum.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Rank                      2 non-null      float64
 1   Name                      2 non-null      object 
 2   City                      2 non-null      object 
 3   State                     2 non-null      object 
 4   Public/Private            2 non-null      object 
 5   Undergraduate Population  2 non-null      float64
 6   Student Population        2 non-null      float64
 7   Net Price                 2 non-null      float64
 8   Average Grant Aid         2 non-null      float64
 9   Total Annual Cost         2 non-null      float64
 10  Alumni Salary             2 non-null      float64
 11  Acceptance Rate           2 non-null      float64
 12  SAT Lower                 2 non-null      float64
 13  SAT Upper                 2 non-null      float64
 14  ACT Lower     

In [19]:
pd.unique(sum['Acceptance Rate'])

array([5.])

In [20]:
sum["Acceptance Rate"].value_counts()

5.0    2
Name: Acceptance Rate, dtype: int64

In [27]:
pd.unique(colleges['State'])

array(['MA', 'CA', 'CT', 'NJ', 'PA', 'RI', 'NC', 'NH', 'NY', 'DC', 'IL',
       'IN', 'MI', 'TX', 'MD', 'ME', 'TN', 'MO', 'VA', 'VT', 'CO', 'MN',
       'GA', 'WA', 'WI', 'FL', 'OH', 'IA', 'UT', 'OR', 'LA', 'SC', 'DE',
       'AL', 'AZ', 'OK', 'NE', 'KY', 'KS', 'AR', 'WY', 'NV', 'MS', 'ND',
       'HI', 'MT', 'SD', 'NM', 'ID', 'WV', 'AK'], dtype=object)

In [30]:
import numpy as np


In [31]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])


In [32]:
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [33]:
pd.isna(array)


array([[False,  True, False],
       [False, False,  True]])

In [34]:
array[0][1]=5

In [35]:
array

array([[ 1.,  5.,  3.],
       [ 4.,  5., nan]])

In [36]:
pd.isna(array)

array([[False, False, False],
       [False, False,  True]])

In [37]:
s = pd.Series(['1.0', '2', -3])

In [38]:
s

0    1.0
1      2
2     -3
dtype: object

In [39]:
pd.to_numeric(s)

0    1.0
1    2.0
2   -3.0
dtype: float64

In [40]:
s[0]=1


In [41]:
s

0     1
1     2
2    -3
dtype: object

In [42]:
pd.to_numeric(s)

0    1
1    2
2   -3
dtype: int64

In [43]:
pd.to_datetime('13000101', format='%Y%m%d', errors='ignore')

datetime.datetime(1300, 1, 1, 0, 0)

In [44]:
testdate = pd.to_datetime('13000101', format='%Y%m%d', errors='ignore')


In [45]:
testdate


datetime.datetime(1300, 1, 1, 0, 0)

In [46]:
s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'] * 1000)

In [47]:
s

0       3/11/2000
1       3/12/2000
2       3/13/2000
3       3/11/2000
4       3/12/2000
          ...    
2995    3/12/2000
2996    3/13/2000
2997    3/11/2000
2998    3/12/2000
2999    3/13/2000
Length: 3000, dtype: object

In [48]:
pd.to_datetime(s, infer_datetime_format=True) 

0      2000-03-11
1      2000-03-12
2      2000-03-13
3      2000-03-11
4      2000-03-12
          ...    
2995   2000-03-12
2996   2000-03-13
2997   2000-03-11
2998   2000-03-12
2999   2000-03-13
Length: 3000, dtype: datetime64[ns]

In [49]:
colleges.columns


Index(['Rank', 'Name', 'City', 'State', 'Public/Private',
       'Undergraduate Population', 'Student Population', 'Net Price',
       'Average Grant Aid', 'Total Annual Cost', 'Alumni Salary',
       'Acceptance Rate', 'SAT Lower', 'SAT Upper', 'ACT Lower', 'ACT Upper',
       'Website'],
      dtype='object')

In [50]:
colleges.index

RangeIndex(start=0, stop=650, step=1)

In [51]:
colleges.dtypes


Rank                        float64
Name                         object
City                         object
State                        object
Public/Private               object
Undergraduate Population    float64
Student Population          float64
Net Price                   float64
Average Grant Aid           float64
Total Annual Cost           float64
Alumni Salary               float64
Acceptance Rate             float64
SAT Lower                   float64
SAT Upper                   float64
ACT Lower                   float64
ACT Upper                   float64
Website                      object
dtype: object

In [52]:
colleges.values

array([[1.0, 'Harvard University', 'Cambridge', ..., 32.0, 35.0,
        'www.harvard.edu'],
       [2.0, 'Stanford University', 'Stanford', ..., 32.0, 35.0,
        'www.stanford.edu'],
       [3.0, 'Yale University', 'New Haven', ..., 32.0, 35.0,
        'www.yale.edu'],
       ...,
       [648.0, 'Emory &amp; Henry College', 'Emory', ..., 19.0, 25.0,
        'www.ehc.edu'],
       [649.0, 'Wells College', 'Aurora', ..., nan, nan, 'www.wells.edu'],
       [650.0, 'Catawba College', 'Salisbury', ..., 18.0, 23.0,
        'www.catawba.edu']], dtype=object)

In [53]:
colleges.shape

(650, 17)

In [57]:
colleges['SAT Lower'].astype('float32')

0      1460.0
1      1390.0
2      1460.0
3      1490.0
4      1430.0
        ...  
645     910.0
646     900.0
647     988.0
648       NaN
649     930.0
Name: SAT Lower, Length: 650, dtype: float32

In [58]:
colleges.loc[0]

Rank                                         1
Name                        Harvard University
City                                 Cambridge
State                                       MA
Public/Private                         Private
Undergraduate Population                 13844
Student Population                       31120
Net Price                                14327
Average Grant Aid                        49870
Total Annual Cost                        69600
Alumni Salary                           146800
Acceptance Rate                              5
SAT Lower                                 1460
SAT Upper                                 1590
ACT Lower                                   32
ACT Upper                                   35
Website                        www.harvard.edu
Name: 0, dtype: object

In [59]:
colleges.loc[:,'Name']

0                         Harvard University
1                        Stanford University
2                            Yale University
3      Massachusetts Institute of Technology
4                       Princeton University
                       ...                  
645              New Mexico State University
646                 Indiana State University
647                Emory &amp; Henry College
648                            Wells College
649                          Catawba College
Name: Name, Length: 650, dtype: object

In [61]:
colleges.loc[:,['Rank','Name']]

Rank                                   Name
0      1.0                     Harvard University
1      2.0                    Stanford University
2      3.0                        Yale University
3      4.0  Massachusetts Institute of Technology
4      5.0                   Princeton University
..     ...                                    ...
645  646.0            New Mexico State University
646  647.0               Indiana State University
647  648.0              Emory &amp; Henry College
648  649.0                          Wells College
649  650.0                        Catawba College

[650 rows x 2 columns]

In [63]:
colleges.iloc[0,[0,1,2]]

Rank                     1
Name    Harvard University
City             Cambridge
Name: 0, dtype: object

In [65]:
colleges.iloc[:2,[0]].apply(lambda x: x.sum(),axis=0)

Rank    3.0
dtype: float64

In [68]:
colleges.loc[:1,['SAT Lower', 'SAT Upper']].apply(lambda x: x.sum(),axis=1)

0    3050.0
1    2930.0
dtype: float64

In [71]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})

In [72]:
df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [73]:
df.dropna()

name        toy       born
1  Batman  Batmobile 1940-04-25

In [74]:

df = pd.DataFrame(
     [
         ("bird", "Falconiformes", 389.0),
         ("bird", "Psittaciformes", 24.0),
            ("mammal", "Carnivora", 80.2),
            ("mammal", "Primates", np.nan),
            ("mammal", "Carnivora", 58),
        ],
        index=["falcon", "parrot", "lion", "monkey", "leopard"],
        columns=("class", "order", "max_speed"),
    )


In [75]:
df

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [79]:
df['class']

falcon       bird
parrot       bird
lion       mammal
monkey     mammal
leopard    mammal
Name: class, dtype: object

In [80]:
df.values

array([['bird', 'Falconiformes', 389.0],
       ['bird', 'Psittaciformes', 24.0],
       ['mammal', 'Carnivora', 80.2],
       ['mammal', 'Primates', nan],
       ['mammal', 'Carnivora', 58.0]], dtype=object)

In [82]:
df.loc["falcon"]

class                 bird
order        Falconiformes
max_speed              389
Name: falcon, dtype: object

In [83]:
df["class"]["falcon"]

'bird'

In [84]:
grouped = df.groupby("class")

In [91]:

for name, group in grouped:
    #print(name)
    print(group)

       class           order  max_speed
falcon  bird   Falconiformes      389.0
parrot  bird  Psittaciformes       24.0
          class      order  max_speed
lion     mammal  Carnivora       80.2
monkey   mammal   Primates        NaN
leopard  mammal  Carnivora       58.0


In [92]:
grouped['max_speed'].mean()

class
bird      206.5
mammal     69.1
Name: max_speed, dtype: float64