In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])

In [3]:
y = np.dot(X, np.array([1, 2])) + 3

In [4]:
y

array([ 6,  8,  9, 11])

In [5]:
reg = LinearRegression().fit(X, y)

In [6]:
reg

LinearRegression()

In [7]:
reg.score(X, y)

1.0

In [8]:
reg.coef_

array([1., 2.])

In [9]:
reg.intercept_

3.000000000000001

In [10]:
reg.predict(np.array([[3, 5]]))

array([16.])